import {
  KPIData,
  TrackSection,
  AIDetection,
  Alert,
  PredictiveRisk,
  Inspection,
  DeviceSensor,
  ReportItem,
  LiveTrain,
  WeatherData,
  WeatherForecastItem,
} from './types';

export const INITIAL_KPIS: KPIData = {
  trackNetworkKm: 4280,
  trackNetworkChangeKm: 12,
  trackHealthPct: 94.8,
  trackHealthStatus: 'STABLE',
  activeAlertsCount: 17,
  criticalAlertsCount: 3,
  aiDetectionsToday: 1284,
  aiDetectionsCapPct: 85,
  maintenanceDueCount: 42,
  openInspectionsCount: 8,
  liveTrainsCount: 47,
  runningTrainsCount: 39,
  delayedTrainsCount: 6,
  weatherCondition: 'Heavy Rain',
  weatherRiskScore: 68,
};

export const MOCK_WEATHER: WeatherData = {
  city: 'New Delhi',
  division: 'Delhi Division (Northern Railway)',
  temperatureC: 29.4,
  feelsLikeC: 34.2,
  humidityPct: 82,
  windSpeedKmh: 28.5,
  windDirectionDeg: 115,
  rainfallMm1h: 14.8,
  visibilityKm: 2.1,
  pressureHpa: 1006,
  condition: 'Heavy Monsoon Rain',
  conditionIcon: 'cloud-rain',
  weatherRiskScore: 68,
  weatherRiskLevel: 'HIGH',
  drainageRisk: 'HIGH (Ballast Saturation & Siding Flooding)',
  bucklingRisk: 'LOW (Rail Temperature Normal at 31°C)',
  catenaryRisk: 'MODERATE (Wind Gusts up to 38 km/h)',
  visibilityRisk: 'MODERATE (Low Cloud Ceiling 350m)',
  trackImpactSummary: 'Heavy monsoon downpour active across NDLS–GZB corridor (+14.8mm/hr). Ballast saturation high on Tuglakabad siding. 60 km/h caution recommended on freight rakes.',
  lastUpdated: '12 sec ago',
  dataSource: 'SIMULATION_FALLBACK',
};

export const MOCK_FORECAST: WeatherForecastItem[] = [
  { time: '18:00', temperatureC: 29.4, condition: 'Heavy Rain', rainfallMm: 14.8, riskScore: 68 },
  { time: '21:00', temperatureC: 27.8, condition: 'Moderate Rain', rainfallMm: 8.2, riskScore: 54 },
  { time: '00:00', temperatureC: 26.5, condition: 'Overcast', rainfallMm: 2.1, riskScore: 38 },
  { time: '03:00', temperatureC: 25.8, condition: 'Light Drizzle', rainfallMm: 0.8, riskScore: 30 },
  { time: '06:00', temperatureC: 26.2, condition: 'Morning Fog', rainfallMm: 0.0, riskScore: 42 },
  { time: '09:00', temperatureC: 29.0, condition: 'Partly Cloudy', rainfallMm: 0.0, riskScore: 22 },
  { time: '12:00', temperatureC: 33.5, condition: 'High Heat', rainfallMm: 0.0, riskScore: 45 },
];

export const LIVE_TRAINS: LiveTrain[] = [
  {
    id: 'TRN-12001',
    trainNumber: '12001',
    trainName: 'Shatabdi Express (Bhopal - New Delhi)',
    latitude: 28.6620,
    longitude: 77.3100,
    speedKmH: 84.0,
    direction: 'WESTBOUND',
    status: 'WARNING',
    currentStation: 'Ghaziabad (GZB)',
    nextStation: 'New Delhi (NDLS)',
    delayMinutes: 4,
    eta: '18:42',
    lastUpdatedSec: 12,
    route: 'Bhopal -> GZB -> NDLS (Mainline Up)',
    nextStations: [
      { name: 'Sahibabad Jn (SBB)', eta: '18:25' },
      { name: 'Anand Vihar (ANVR)', eta: '18:32' },
      { name: 'New Delhi (NDLS)', eta: '18:42' },
    ],
    approachingAlert: {
      alertId: 'ALT-CRIT-TRN-12001',
      trainNumber: '12001',
      trainName: 'Shatabdi Express',
      defectId: 'DET-2026-0892',
      defectType: 'Transverse Rail Fracture Crack',
      locationKm: 'KM 142.6 (Mainline Up)',
      distanceKm: 3.2,
      speedKmH: 84.0,
      etaMinutes: 2.3,
      etaFormatted: '2m 18s',
      riskLevel: 'CRITICAL',
      recommendedAction: 'Issue immediate 30 km/h Caution Order & alert Loco Pilot via RTIS / Kavach radio.',
      timestamp: 'Just now',
    },
    dataSource: 'SIMULATION_FALLBACK',
  },
  {
    id: 'TRN-12424',
    trainNumber: '12424',
    trainName: 'Dibrugarh Rajdhani Express',
    latitude: 28.7200,
    longitude: 77.1700,
    speedKmH: 110.0,
    direction: 'NORTHBOUND',
    status: 'RUNNING',
    currentStation: 'Old Delhi (DLI)',
    nextStation: 'Panipat Jn (PNP)',
    delayMinutes: 0,
    eta: '19:15',
    lastUpdatedSec: 8,
    route: 'NDLS -> DLI -> UMB -> DBRG',
    nextStations: [
      { name: 'Sonipat (SNP)', eta: '18:50' },
      { name: 'Panipat (PNP)', eta: '19:15' },
      { name: 'Ambala Cantt (UMB)', eta: '20:30' },
    ],
    dataSource: 'SIMULATION_FALLBACK',
  },
  {
    id: 'TRN-22436',
    trainNumber: '22436',
    trainName: 'Vande Bharat Express (Varanasi - NDLS)',
    latitude: 28.4500,
    longitude: 77.3100,
    speedKmH: 130.0,
    direction: 'NORTHBOUND',
    status: 'RUNNING',
    currentStation: 'Mathura Jn (MTJ)',
    nextStation: 'Hazrat Nizamuddin (NZM)',
    delayMinutes: 0,
    eta: '18:55',
    lastUpdatedSec: 4,
    route: 'BSB -> CNB -> ALJN -> NDLS',
    nextStations: [
      { name: 'Palwal (PWL)', eta: '18:18' },
      { name: 'Faridabad (FDB)', eta: '18:38' },
      { name: 'New Delhi (NDLS)', eta: '18:55' },
    ],
    dataSource: 'SIMULATION_FALLBACK',
  },
  {
    id: 'TRN-14041',
    trainNumber: '14041',
    trainName: 'Mussoorie Express',
    latitude: 28.5800,
    longitude: 77.2400,
    speedKmH: 48.0,
    direction: 'SOUTHBOUND',
    status: 'DELAYED',
    currentStation: 'Tuglakabad Yard (TKD)',
    nextStation: 'Faridabad (FDB)',
    delayMinutes: 22,
    eta: '19:40',
    lastUpdatedSec: 18,
    route: 'DLI -> TKD -> FDB -> KOTA',
    nextStations: [
      { name: 'Ballabgarh (BVH)', eta: '19:55' },
      { name: 'Palwal (PWL)', eta: '20:25' },
    ],
    dataSource: 'SIMULATION_FALLBACK',
  },
  {
    id: 'TRN-BOXN-4028',
    trainNumber: 'BOXN-4028',
    trainName: 'Coal Freight Rake #4028',
    latitude: 28.5742,
    longitude: 77.2481,
    speedKmH: 55.0,
    direction: 'SOUTHBOUND',
    status: 'RUNNING',
    currentStation: 'Tuglakabad Siding',
    nextStation: 'Dadri DFC Yard',
    delayMinutes: 0,
    eta: '21:00',
    lastUpdatedSec: 15,
    route: 'TKD Freight Corridor -> DFC',
    nextStations: [{ name: 'Dadri Freight Hub', eta: '21:00' }],
    dataSource: 'SIMULATION_FALLBACK',
  },
];

export const TRACK_SECTIONS: TrackSection[] = [
  {
    id: 'SEC-NDLS-GZB-01',
    code: 'NDLS-S1A',
    name: 'New Delhi – Ghaziabad Mainline Up',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    startKm: 140.0,
    endKm: 155.0,
    healthScore: 78.4,
    status: 'critical',
    coordinates: [
      [28.6429, 77.2195],
      [28.6500, 77.2500],
      [28.6620, 77.3100],
      [28.6700, 77.4200],
    ],
    center: [28.655, 77.29],
    railType: '60kg UIC-90 UTS',
    sleepersCount: 24800,
    lineSpeedLimitKmH: 130,
    lastInspected: '2026-08-15 08:30',
    activeDefectsCount: 4,
  },
  {
    id: 'SEC-NDLS-TKD-02',
    code: 'NDLS-TKD-DN',
    name: 'New Delhi – Tuglakabad Freight Corridor',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    startKm: 80.0,
    endKm: 98.5,
    healthScore: 88.2,
    status: 'warning',
    coordinates: [
      [28.6429, 77.2195],
      [28.5800, 77.2400],
      [28.5100, 77.2800],
    ],
    center: [28.57, 77.25],
    railType: '60kg Head Hardened',
    sleepersCount: 31200,
    lineSpeedLimitKmH: 100,
    lastInspected: '2026-08-14 16:15',
    activeDefectsCount: 2,
  },
  {
    id: 'SEC-DLI-UMB-03',
    code: 'DLI-UMB-UP',
    name: 'Old Delhi – Ambala Cantt High-Density Route',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    startKm: 10.0,
    endKm: 45.0,
    healthScore: 97.6,
    status: 'optimal',
    coordinates: [
      [28.6600, 77.2280],
      [28.7200, 77.1700],
      [28.8500, 77.0800],
    ],
    center: [28.75, 77.16],
    railType: '60kg UIC-90 UTS',
    sleepersCount: 56000,
    lineSpeedLimitKmH: 160,
    lastInspected: '2026-08-15 11:00',
    activeDefectsCount: 0,
  },
  {
    id: 'SEC-ANVR-MB-04',
    code: 'ANVR-MB-02',
    name: 'Anand Vihar – Moradabad Fast Corridor',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    startKm: 5.0,
    endKm: 32.0,
    healthScore: 95.1,
    status: 'optimal',
    coordinates: [
      [28.6500, 77.3150],
      [28.6400, 77.3900],
      [28.6300, 77.5200],
    ],
    center: [28.64, 77.41],
    railType: '60kg Head Hardened',
    sleepersCount: 43200,
    lineSpeedLimitKmH: 130,
    lastInspected: '2026-08-13 14:20',
    activeDefectsCount: 1,
  },
  {
    id: 'SEC-NZM-AGC-05',
    code: 'NZM-AGC-UP',
    name: 'Hazrat Nizamuddin – Agra Cantt Semi-High Speed',
    zone: 'Northern Railway',
    division: 'Delhi Division',
    startKm: 0.0,
    endKm: 60.0,
    healthScore: 98.9,
    status: 'optimal',
    coordinates: [
      [28.5880, 77.2530],
      [28.4500, 77.3100],
      [28.2500, 77.3800],
    ],
    center: [28.42, 77.31],
    railType: '60kg UIC-90 UTS',
    sleepersCount: 96000,
    lineSpeedLimitKmH: 160,
    lastInspected: '2026-08-15 06:45',
    activeDefectsCount: 0,
  },
];

export const AI_DETECTIONS: AIDetection[] = [
  {
    id: 'DET-2026-0892',
    detectionCode: '#TF-8992',
    defectType: 'Transverse Rail Fracture Crack',
    severity: 'critical',
    confidence: 96.8,
    trackSectionId: 'SEC-NDLS-GZB-01',
    trackSectionName: 'New Delhi – Ghaziabad Mainline Up',
    locationKm: 142.6,
    coordinates: { lat: 28.6554, lng: 77.2912 },
    segmentCode: 'NDLS-S1A',
    timestamp: '2026-08-15 14:22:05 UTC',
    cameraRef: 'Cam-04 (High-Res IR)',
    lineSpeedKmH: 85,
    ambientTempC: 34,
    estimatedDepthMm: 14,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0poUvT85sYQ6T2ZcZWDt8OKia-66TP7GqCQeJnPRQxTZC4q4uZFfJGcH56tTORq1hqSjFUomLdHT4sj1i6W1_IODl_YLpfPpGslpAvfSU-hc3vJSvEklhz9P80MwMTY20NzhBvVEMuDuT3r5zR5HMYctZmkKBO2yfko-EnlEbbxuBzRxIJz0_lACABZnNmqLG1GF5t73Z3B_mSH1Zc8z0kWHUk7LSqUhPl5tkQ1xbb5vr7AJN7v6n',
    boundingBox: {
      x: 42,
      y: 38,
      width: 22,
      height: 28,
      label: 'TF-CRACK DETECTED',
    },
    reasoningFactors: [
      {
        title: 'Pattern match: Transverse Fissure (TF)',
        description: 'Deep neural feature match with 98.2% weight on ResNet-50-Rail (v2.4)',
        category: 'model_match',
        confidenceWeightPct: 98.2,
      },
      {
        title: 'Growth detected from previous scan',
        description: '+2.4mm expansion detected compared to baseline scan (12 days prior)',
        category: 'trend',
        confidenceWeightPct: 94.0,
      },
      {
        title: 'Acoustic Emission Confirmation',
        description: 'Acoustic sensor TRK-2048 recorded high-frequency stress wave peak at 14:21:58',
        category: 'acoustic_signature',
        confidenceWeightPct: 91.5,
      },
    ],
    recommendedAction: 'Immediate manual inspection required. Speed restriction of 30 km/h recommended until verification.',
    status: 'pending_verification',
    assignedEngineer: 'Er. Rajesh Sharma (SE/P-Way)',
    notes: 'Located on right rail head near fishplate weld point.',
  },
  {
    id: 'DET-2026-0893',
    detectionCode: '#FA-4412',
    defectType: 'Fastener Missing / Loose Anomaly',
    severity: 'high',
    confidence: 68.4,
    trackSectionId: 'SEC-NDLS-TKD-02',
    trackSectionName: 'New Delhi – Tuglakabad Freight Corridor',
    locationKm: 88.2,
    coordinates: { lat: 28.5742, lng: 77.2481 },
    segmentCode: 'TKD-F3',
    timestamp: '2026-08-15 13:48:10 UTC',
    cameraRef: 'Cam-02 (Optical Bogie Scanner)',
    lineSpeedKmH: 60,
    ambientTempC: 36,
    estimatedDepthMm: 0,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0poUvT85sYQ6T2ZcZWDt8OKia-66TP7GqCQeJnPRQxTZC4q4uZFfJGcH56tTORq1hqSjFUomLdHT4sj1i6W1_IODl_YLpfPpGslpAvfSU-hc3vJSvEklhz9P80MwMTY20NzhBvVEMuDuT3r5zR5HMYctZmkKBO2yfko-EnlEbbxuBzRxIJz0_lACABZnNmqLG1GF5t73Z3B_mSH1Zc8z0kWHUk7LSqUhPl5tkQ1xbb5vr7AJN7v6n',
    boundingBox: {
      x: 60,
      y: 50,
      width: 18,
      height: 20,
      label: 'FASTENER DISLODGED',
    },
    reasoningFactors: [
      {
        title: 'Elastic Rail Clip (ERC) Displacement',
        description: 'Clip angle deviation exceeds 15 degrees from sleeper housing',
        category: 'model_match',
        confidenceWeightPct: 68.4,
      },
      {
        title: 'Sleeper Vibration Signature',
        description: 'Accelerometer node reported micro-impact spike during freight train passage',
        category: 'sensor_correlation',
        confidenceWeightPct: 72.0,
      },
    ],
    recommendedAction: 'Human verification required. Schedule trackman gang inspection within 24 hours.',
    status: 'pending_verification',
    assignedEngineer: 'Er. Amit Verma',
    notes: 'Two consecutive ERC clips displaced on Sleeper #4402.',
  },
  {
    id: 'DET-2026-0894',
    detectionCode: '#VEG-1109',
    defectType: 'Vegetation Encroachment',
    severity: 'routine',
    confidence: 89.1,
    trackSectionId: 'SEC-DLI-UMB-03',
    trackSectionName: 'Old Delhi – Ambala Cantt High-Density Route',
    locationKm: 210.5,
    coordinates: { lat: 28.7511, lng: 77.1622 },
    segmentCode: 'DLI-UMB-BR',
    timestamp: '2026-08-15 11:15:32 UTC',
    cameraRef: 'Cam-01 (Forward Wide-Angle)',
    lineSpeedKmH: 110,
    ambientTempC: 31,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0poUvT85sYQ6T2ZcZWDt8OKia-66TP7GqCQeJnPRQxTZC4q4uZFfJGcH56tTORq1hqSjFUomLdHT4sj1i6W1_IODl_YLpfPpGslpAvfSU-hc3vJSvEklhz9P80MwMTY20NzhBvVEMuDuT3r5zR5HMYctZmkKBO2yfko-EnlEbbxuBzRxIJz0_lACABZnNmqLG1GF5t73Z3B_mSH1Zc8z0kWHUk7LSqUhPl5tkQ1xbb5vr7AJN7v6n',
    boundingBox: {
      x: 15,
      y: 20,
      width: 25,
      height: 35,
      label: 'VEGETATION WITHIN 2.5M CLEARANCE',
    },
    reasoningFactors: [
      {
        title: 'Structure Gauge Obstruction',
        description: 'Tree foliage encroaching into the 2.5-meter kinematic envelope',
        category: 'model_match',
        confidenceWeightPct: 89.1,
      },
    ],
    recommendedAction: 'Schedule routine vegetation trimming gang during next maintenance block.',
    status: 'confirmed',
    assignedEngineer: 'Section Engineer Horticulture & P-Way',
    notes: 'No immediate contact with catenary wire.',
  },
  {
    id: 'DET-2026-0895',
    detectionCode: '#MIS-5501',
    defectType: 'Track Gauge Misalignment (+8mm)',
    severity: 'high',
    confidence: 94.2,
    trackSectionId: 'SEC-NDLS-GZB-01',
    trackSectionName: 'New Delhi – Ghaziabad Mainline Up',
    locationKm: 147.2,
    coordinates: { lat: 28.6612, lng: 77.3088 },
    segmentCode: 'NDLS-GZB-147',
    timestamp: '2026-08-15 09:40:12 UTC',
    cameraRef: 'Laser Track Geometry Trolley',
    lineSpeedKmH: 45,
    ambientTempC: 33,
    estimatedDepthMm: 8,
    reasoningFactors: [
      {
        title: 'Optical Triangulation Profiling',
        description: 'Track gauge expanded from standard 1676mm to 1684mm over a 12-meter span',
        category: 'model_match',
        confidenceWeightPct: 94.2,
      },
    ],
    recommendedAction: 'Execute tamping and re-gauging during tonight night-block (01:00-04:00).',
    status: 'maintenance_scheduled',
    assignedEngineer: 'Track Machine Division (TMM)',
  },
];

export const PREDICTIVE_RISKS: PredictiveRisk[] = [
  {
    id: 'RISK-2026-01',
    riskTitle: 'Rail Joint Failure Risk',
    component: 'Fishplate & Thermite Welded Joint',
    trackSection: 'Northern Line (KM 142–145)',
    locationKm: 'KM 142.6',
    failureProbability: 81,
    baseRiskPct: 72,
    weatherImpactPct: 9,
    weatherCondition: 'Heavy Monsoon Rain (+9% Saturation)',
    expectedWindowDays: 'Next 8–14 Days',
    priority: 'critical',
    status: 'monitoring',
    contributingFactors: [
      { factor: 'Vibration Amplitude Spike', value: '+42% over baseline', impact: 'critical' },
      { factor: 'Monsoon Ballast Saturation', value: '82% moisture index', impact: 'high' },
      { factor: 'Diurnal Thermal Gradient', value: 'Δ 28°C (Extreme expansion)', impact: 'high' },
      { factor: 'Track Geometry Deviation', value: '4.2mm lateral sag', impact: 'high' },
    ],
    forecastCurve: [
      { day: 'Day 1', riskScore: 45, threshold: 75 },
      { day: 'Day 3', riskScore: 52, threshold: 75 },
      { day: 'Day 7', riskScore: 68, threshold: 75 },
      { day: 'Day 10', riskScore: 76, threshold: 75 },
      { day: 'Day 14', riskScore: 81, threshold: 75 },
      { day: 'Day 21', riskScore: 92, threshold: 75 },
      { day: 'Day 30', riskScore: 98, threshold: 75 },
    ],
    recommendedMaintenance: 'Ultrasonic flaw test (USFD) & immediate thermite weld replacement with flash-butt weld.',
  },
  {
    id: 'RISK-2026-02',
    riskTitle: 'Ballast Degradation & Pumping',
    component: 'Sub-ballast Foundation',
    trackSection: 'Tuglakabad Freight Yard (KM 84–88)',
    locationKm: 'KM 86.1',
    failureProbability: 73,
    baseRiskPct: 61,
    weatherImpactPct: 12,
    weatherCondition: 'Continuous Downpour (+12% Flooding)',
    expectedWindowDays: 'Next 20–30 Days',
    priority: 'high',
    status: 'monitoring',
    contributingFactors: [
      { factor: 'Waterlogged Subgrade Index', value: '78% Saturation', impact: 'high' },
      { factor: 'Axle Load Exceedance', value: '25-tonne heavy freight passes', impact: 'high' },
      { factor: 'Ballast Fouling Ratio', value: '32% fines accumulation', impact: 'medium' },
    ],
    forecastCurve: [
      { day: 'Day 1', riskScore: 30, threshold: 70 },
      { day: 'Day 7', riskScore: 42, threshold: 70 },
      { day: 'Day 14', riskScore: 55, threshold: 70 },
      { day: 'Day 21', riskScore: 66, threshold: 70 },
      { day: 'Day 30', riskScore: 73, threshold: 70 },
    ],
    recommendedMaintenance: 'Deploy Ballast Cleaning Machine (BCM) and deep screening of shoulder ballast.',
  },
  {
    id: 'RISK-2026-03',
    riskTitle: 'Sleepers Micro-Cracking Propagation',
    component: 'Pre-stressed Concrete Sleeper (PSC)',
    trackSection: 'Delhi – Ambala Line (KM 28–32)',
    locationKm: 'KM 30.4',
    failureProbability: 58,
    baseRiskPct: 54,
    weatherImpactPct: 4,
    weatherCondition: 'Thermal Cycling (+4%)',
    expectedWindowDays: 'Next 45–60 Days',
    priority: 'medium',
    status: 'monitoring',
    contributingFactors: [
      { factor: 'Age of Sleeper Batch', value: '14.2 Years in service', impact: 'medium' },
      { factor: 'Dynamic Impact Factor', value: '1.45 at 130 km/h', impact: 'medium' },
    ],
    forecastCurve: [
      { day: 'Day 1', riskScore: 20, threshold: 65 },
      { day: 'Day 15', riskScore: 32, threshold: 65 },
      { day: 'Day 30', riskScore: 44, threshold: 65 },
      { day: 'Day 60', riskScore: 58, threshold: 65 },
      { day: 'Day 90', riskScore: 72, threshold: 65 },
    ],
    recommendedMaintenance: 'Sample sleeper ultrasonic resonant frequency test; planned replacement of 60 PSC sleepers.',
  },
];

export const ALERTS: Alert[] = [
  {
    id: 'ALT-1000',
    alertCode: 'ALT-CRIT-TRN-12001',
    title: 'Train 12001 Approaching Critical Rail Crack (3.2 km / 2m 18s ETA)',
    severity: 'critical',
    trackSection: 'New Delhi – Ghaziabad Mainline Up',
    locationKm: 142.6,
    detectionSource: 'Train Proximity Correlation + Computer Vision',
    timestamp: 'Just now',
    aiConfidence: 96.8,
    status: 'active',
    assignedEngineer: 'Er. Rajesh Sharma (SE/P-Way)',
    notes: 'AUTOMATED CAUTION ORDER: Speed restriction of 30 km/h sent to Loco Pilot.',
  },
  {
    id: 'ALT-1001',
    alertCode: 'ALT-CRIT-001',
    title: 'Severe Rail Fracture Detected (KM 142.6)',
    severity: 'critical',
    trackSection: 'New Delhi – Ghaziabad Mainline Up',
    locationKm: 142.6,
    detectionSource: 'Computer Vision IR + Acoustic Telemetry',
    timestamp: '12 mins ago',
    aiConfidence: 96.8,
    status: 'active',
    assignedEngineer: 'Er. Rajesh Sharma (SE/P-Way)',
    notes: 'Caution order issued: 30 km/h imposed on section.',
  },
  {
    id: 'ALT-1002',
    alertCode: 'ALT-CRIT-002',
    title: 'Heavy Monsoon Downpour & Ballast Waterlogging (+14.8mm/h)',
    severity: 'high',
    trackSection: 'Tuglakabad Yard Freight Siding',
    locationKm: 86.1,
    detectionSource: 'Weather Risk Engine + Wayside DTS Loop',
    timestamp: '20 mins ago',
    aiConfidence: 94.0,
    status: 'active',
    assignedEngineer: 'Monsoon Patrolling Gang #2',
    notes: 'High drainage saturation index. Slow order 60 km/h active.',
  },
  {
    id: 'ALT-1003',
    alertCode: 'ALT-CRIT-003',
    title: 'Track Obstruction on Gauge Clearance (KM 18.2)',
    severity: 'critical',
    trackSection: 'Anand Vihar Corridor',
    locationKm: 18.2,
    detectionSource: 'Loco-Cam AI Video Feed',
    timestamp: '45 mins ago',
    aiConfidence: 92.4,
    status: 'in_progress',
    assignedEngineer: 'RPF Quick Reaction Team & P-Way',
    notes: 'RPF team reached site; obstruction clearing in progress.',
  },
  {
    id: 'ALT-1004',
    alertCode: 'ALT-HIGH-004',
    title: 'Fasteners Dislodged on Sleeper Cluster #4402',
    severity: 'high',
    trackSection: 'Tuglakabad Freight Line',
    locationKm: 88.2,
    detectionSource: 'Inspection Vehicle TRC-04',
    timestamp: '1 hour ago',
    aiConfidence: 68.4,
    status: 'acknowledged',
    assignedEngineer: 'Er. Amit Verma',
  },
  {
    id: 'ALT-1005',
    alertCode: 'ALT-MED-005',
    title: 'Reduced Fog Visibility (< 2.1 km) on Northern Line',
    severity: 'medium',
    trackSection: 'Old Delhi – Ambala Cantt Route',
    locationKm: 34.8,
    detectionSource: 'OpenWeather Radar Feed',
    timestamp: '2 hours ago',
    aiConfidence: 98.0,
    status: 'acknowledged',
    assignedEngineer: 'Control Room Duty Officer',
  },
];

export const INSPECTIONS: Inspection[] = [
  {
    id: 'INS-2026-084',
    inspectionCode: 'INS-RD-884A',
    trackSection: 'New Delhi – Ghaziabad Mainline Up (KM 140–155)',
    inspectorName: 'Er. Vikramaditya Singh',
    inspectorRole: 'Senior Divisional Engineer (Track)',
    date: '2026-08-15',
    timeSlot: '14:00 - 18:00',
    status: 'in_progress',
    vehicleType: 'Track Recording Car (TRC-2000)',
    defectsFound: 4,
    criticalCount: 1,
    complianceScorePct: 82.5,
    notes: 'Focused ultrasound scan of high-density junction welds.',
  },
  {
    id: 'INS-2026-085',
    inspectionCode: 'INS-RD-885B',
    trackSection: 'Old Delhi – Ambala Section (KM 10–45)',
    inspectorName: 'Er. Meenakshi Rao',
    inspectorRole: 'Assistant Divisional Engineer (P-Way)',
    date: '2026-08-16',
    timeSlot: '06:00 - 10:00',
    status: 'scheduled',
    vehicleType: 'Autonomous AI Drone + LiDAR',
    defectsFound: 0,
    criticalCount: 0,
    complianceScorePct: 98.0,
    notes: 'Catenary wire sag and clearance verification.',
  },
  {
    id: 'INS-2026-082',
    inspectionCode: 'INS-RD-882C',
    trackSection: 'Tuglakabad – Faridabad Corridor (KM 80–98)',
    inspectorName: 'Er. Rajesh Sharma',
    inspectorRole: 'Senior Section Engineer (P-Way)',
    date: '2026-08-14',
    timeSlot: '10:00 - 14:00',
    status: 'completed',
    vehicleType: 'Motorized Inspection Trolley (MIT-08)',
    defectsFound: 3,
    criticalCount: 0,
    complianceScorePct: 91.0,
    notes: 'Fastener torque test and ballast shoulder profile survey.',
  },
  {
    id: 'INS-2026-079',
    inspectionCode: 'INS-RD-079X',
    trackSection: 'Anand Vihar Fast Line (KM 5–32)',
    inspectorName: 'Er. Amit Verma',
    inspectorRole: 'Junior Engineer (Civil)',
    date: '2026-08-12',
    timeSlot: '01:00 - 04:30',
    status: 'overdue',
    vehicleType: 'Manual Foot Inspection Gang',
    defectsFound: 6,
    criticalCount: 2,
    complianceScorePct: 69.0,
    notes: 'Night block missed due to heavy goods traffic; rescheduled for urgent review.',
  },
];

export const SENSOR_DEVICES: DeviceSensor[] = [
  {
    id: 'DEV-TRK-2048',
    deviceCode: 'TRK-2048',
    name: 'Acoustic Emission Stress Detector',
    type: 'acoustic',
    location: 'NDLS-S1A Joint (KM 142.6)',
    trackKm: 142.6,
    status: 'online',
    batteryPct: 87,
    signalStrengthDbm: -62,
    lastCommunicationSec: 12,
    sampleRateHz: 50000,
    telemetry: {
      vibrationG: 1.84,
      temperatureC: 34.2,
      strainMicrostrain: 480,
      voltageV: 12.4,
    },
  },
  {
    id: 'DEV-DTS-009',
    deviceCode: 'DTS-FIBER-09',
    name: 'Distributed Temperature Sensor (DTS)',
    type: 'dts_fiber',
    location: 'DLI-UMB High-Speed Route (KM 34.8)',
    trackKm: 34.8,
    status: 'online',
    batteryPct: 99,
    signalStrengthDbm: -54,
    lastCommunicationSec: 4,
    sampleRateHz: 100,
    telemetry: {
      temperatureC: 58.4,
      voltageV: 24.0,
    },
  },
  {
    id: 'DEV-CAM-04',
    deviceCode: 'CAM-IR-04',
    name: 'High-Res Infrared Diagnostic Camera',
    type: 'cctv_ir',
    location: 'Inspection Loco Engine Front #WAP7-3028',
    trackKm: 142.6,
    status: 'online',
    batteryPct: 94,
    signalStrengthDbm: -58,
    lastCommunicationSec: 2,
    sampleRateHz: 60,
    telemetry: {
      temperatureC: 38.0,
      voltageV: 48.0,
    },
  },
  {
    id: 'DEV-ACC-110',
    deviceCode: 'ACC-AXLE-110',
    name: 'Tri-Axial MEMS Accelerometer',
    type: 'accelerometer',
    location: 'Tuglakabad Yard Siding (KM 88.2)',
    trackKm: 88.2,
    status: 'warning',
    batteryPct: 24,
    signalStrengthDbm: -84,
    lastCommunicationSec: 48,
    sampleRateHz: 2000,
    telemetry: {
      vibrationG: 4.12,
      temperatureC: 39.5,
      voltageV: 3.3,
    },
  },
  {
    id: 'DEV-GPS-07',
    deviceCode: 'GPS-TRL-07',
    name: 'Differential GPS Track Geometry Unit',
    type: 'gps_trolley',
    location: 'Anand Vihar Corridor (KM 18.2)',
    trackKm: 18.2,
    status: 'offline',
    batteryPct: 5,
    signalStrengthDbm: -110,
    lastCommunicationSec: 1840,
    sampleRateHz: 20,
    telemetry: {
      voltageV: 2.8,
    },
  },
];

export const REPORTS: ReportItem[] = [
  {
    id: 'REP-2026-0815',
    title: 'Daily Railway Infrastructure & Safety Audit',
    reportType: 'daily_safety',
    division: 'Delhi Division',
    period: '2026-08-15 (00:00 - 24:00)',
    generatedAt: '2026-08-15 17:00 IST',
    generatedBy: 'AI System Autonomous Engine',
    fileFormat: 'PDF',
    fileSizeMb: 4.8,
    summaryMetrics: {
      inspectionsCompleted: 8,
      defectsIdentified: 14,
      criticalAlerts: 3,
      averageHealthScore: 94.8,
    },
  },
];
